
# Spring Configuration
server: 
  port: 8580
  servlet:
    context-path:  ${BILLING_PREFIX:/}


# Logging Configuration
logging:
  level:
    it.eng.dome: ${LOG_LEVEL:DEBUG}
    org.apache.coyote.http11: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%-5level] %logger{36} - %msg%n" 
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Spring Boot Actuator
management:
  server:
    port: 9005
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
      show-details: never
  health:
    probes:
      enabled: true

cache:
  duration: 
    health-service: 1m
    plan-service: 1h
    reporting-service: 1h
    statement-service: 1h
    subscription-service: 1h
    tmforum-service: 1h
    tmforum-list-service: 30m

# Billing Service
billing:
  invoicing_service: ${INVOICING_SERVICE:http://localhost:8380}

tmforumapi:
  #tmf_endpoint: ${TMF_ENDPOINT:https://dome-dev.eng.it}
  tmf_endpoint: ${TMF_ENDPOINT:https://tmf.dome-marketplace-sbx.org}

  tmf_envoy:  ${TMF_ENVOY:true}
  # valid only if envoy false
  tmf_namespace:  ${TMF_NAMESPACE:marketplace}
  tmf_postfix:  ${TMF_POSTFIX:svc.cluster.local}
  tmf_port:  ${TMF_PORT:8080}
   
#  tmf_endpoint: http://localhost:8100
  tmf620_product_catalog_management_path: tmf-api/productCatalogManagement/v4
  tmf629_customer_management_path: tmf-api/customerManagement/v4
  tmf632_party_management_path: tmf-api/party/v4
  tmf637_inventory_path: tmf-api/productInventory/v4
  tmf651_agreement_management_path: tmf-api/agreementManagement/v4
  #tmf666_account_management_path: tmf-api/accountManagement/v4
  tmf678_billing_path: tmf-api/customerBillManagement/v4

# Dome Operator configuration
dome:
  operator:
    id: ${DOME_OPERATOR_ID:urn:ngsi-ld:organization:95fdc12e-6889-4f08-8ff8-296b10e8e781} 
    #id: ${DOME_OPERATOR_ID:urn:ngsi-ld:organization:a195013a-a0e4-493a-810a-b040e10da58f}

caching:
  tmf:
    enabled: true
  revenue:
    enabled: false
  health:
    enabled: true

persistence:
  monthsBack: ${MONTHS_BACK:2}

spring:
  web:
    resources:
      static-locations: file:./src/main/resources/public

dev:
  use-local-plans: true
  enable-web-dashboard: false